### ISSUE TITLE
Ability to specify same flavor and image under a different pool name

### ISSUE THREAD

**Issue by gustaff-weldon** [mercedes-benz/garm-operator#139]
### What is the feature you would like to have?

We are using logical pool names created not after runner size, but after purpose. Thus we might have two runner pools with the same machine flavor under two names, as we manage underlying machine size independently for each pool.
Atm, operator disallows cration of such pools if flavor, image and repository are the same (even if name differs).

```
Error: failed to create resource: admission webhook "validate.pool.garm-operator.mercedes-benz.com" 
denied the request: can not create pool, pool=medium with same image=ubuntu-22, flavor=e2-standard-4 
and provider=gcp_external already exists for specified GitHubScope=monorepo
```

We would like ability to lessen that limitation.

**Comment by gustaff-weldon** [comment]
Also, the admission webhook seems to not work properly (race condition) as I was able to create two pools with the same flavor:
[
![Screenshot 2024-06-28 at 14 47 27](https://github.com/mercedes-benz/garm-operator/assets/411756/61aeb2f2-1db0-4827-8b29-4eaf75ebf2e3)
](url)

**Comment by bavarianbidi** [comment]
Hey @gustaff-weldon thanks for raising this issue and for using the operator :pray: 

The reason for that limitation is a `garm` limitation which exists till `v0.1.4`.
Gabriel removed that limitation in https://github.com/cloudbase/garm/pull/246

I'm not sure yet, if we should extend the operator in that way, that versions `<= v0.1.4` are supported or explicitly pin operator versions to certain garm versions.
