### ISSUE TITLE
`garm` server configuration should be possible via `garm-operator`

### ISSUE THREAD

**Issue by bavarianbidi** [mercedes-benz/garm-operator#143]
### What is the feature you would like to have?

With the recent changes in `garm` (and also future ideas in the backlog) it will be possible to "configure" a `garm-server` instance in a declarative way.
The current version of `garm-operator` already takes care of the circumstance if a garm-instance is initialized or not and takes care of the initialization if needed.

As we already check on every api-request for an initialed garm-server ([func Ensured Auth](https://github.com/mercedes-benz/garm-operator/blob/main/pkg/client/client.go#L197-L215)) we should at least decouple this implementation and use some existing primitives of kubernetes to make the code a bit more easier to read.

I would like to see a dedicated controller with is responsible for the generic garm-server management and controllers for scoped resources (Separation of concerns). 

Current known resources

| name | scope | depends_on |
| --- | --- | --- |
| github endpoint | shared across github credentials | |
| github credentials | shared across orgs/repos/enterprises | github endpoint | 
| webhooks | | | 
| repo/org | | github credentials |
| pool | | repo/org, enterprise |
| enterprise | | github credentials |
| image | shared across pools |  |

### Anything else you would like to add?

As the configuration of the github backend has already moved out of a config file and moved into the api (with https://github.com/cloudbase/garm/pull/243) and we have an issue for this (https://github.com/mercedes-benz/garm-operator/issues/127) we should agree on the separation level first.

How could the new CRs look like? Maybe we can "design" the CRs first before start implementing :pray:

**Comment by bavarianbidi** [comment]
cc @gabriel-samfira - as you already have similar thoughts about managing garm itself via the operator: would be nice if you could drop some of your thoughts about this in here :pray:

**Comment by gabriel-samfira** [comment]
I've actually started playing around with this here: https://github.com/gabriel-samfira/garm-operator/tree/add-garm-server-controller

However I've been sidetracked a bit. Hopefully I can resume soon.

The basic idea is as follows:

* A new CR is created to describe the garm-server
* A single CRD should be allowed (perhaps created automatically) that describes the managed garm server
* Perhaps allow the controller to be disabled and use an external garm server, in which case things should work as they do now (not sure about this)
* The controller is responsible for composing the GARM config file
* GARM now returns the version it's running as part of the controller info API.
  * Using this version we can decide if the credentials/providers should be composed as part of the config or as database entries. v0.1.4 and bellow requires a config entry. From 0.1.5 (not yet released), credentials are in the config. Providers will perhaps be moved to the DB starting with v0.1.6.
  * The lack of a version in the controller info will make the operator assume the version is <= v0.1.4
* New CR will be added for:
  * Github Endpoints
  * Github credentials
  * Providers. This might be split up in the future into provider types and provider endpoints. The provider type will indicate the cloud which that provider is meant for. The provider endpoint will be a set of credentials for that cloud. This is not yet set in stone, comments and ideas are welcome. This will be slatd for v0.1.6 or v0.1.7.
* The garm server operator will list all github endpoints, all gh credentials and all providers and along with the settings specified by the user for the garm server CRD, a valid TOML config will be composed and set as a config map.
* That config map will be mounted as the garm-server config file and the server will be started.
* Status will be set to Ready for the garm server, at which point the garm client can be instantiated and the rest of the operators will be unblocked to reconcile to their heart's contempt.

This is just a rough idea so far. What do you think?

**Comment by bavarianbidi** [comment]
i'm not sure if i got the entire idea :see_no_evil: 

are you even go one step further to manage the `garm-server` Deployment object (incl. `Service`, ... ) or is it more like "generating and creating/updating the configmap in k8s"?
If so, the "state" of the `garm-server` Deployment is managed by two dedicated controllers/components:
* configmap (and image if i got your working branch right) are managed by the operator
* everything else which belongs to the `garm-server` belongs to another tool (e.g. flux/argocd or a semi-automatic github action deploy workflow)

**Comment by gabriel-samfira** [comment]
The controller would manage a StatefulSet which is the garm-server itself. Not sure if it's worth having separate controllers for config map management. I think we could fit that into the reconciliation loop of the garm server controller.

the reconciliation loop would basically use the CRD settings to compose the config map, save the config map, update the stateful set. If we add CRs for credentials and providers, we just add those two types in the loop as well. List al creds/providers, get CRD settings, compose config map, update stateful set.

The controller can watch for changes to credentials, providers and the garm server CRD (which it owns) and react accordingly.

For credentials and providers we need separate controllers/webhooks.

I think the best way to go about it would be to create a WiP branch and discuss it once it's ready. Doesn't seem to difficult to write a controller using kubebuilder. An initial draft would be without tests and not necessarily correct, but would give everyone a view of the rough idea.

**Comment by gabriel-samfira** [comment]
You're right. That makes a lot of sense. A proper helm chart is definitely preferable to reinventing the wheel. In that case, we should be fine with just implementing the resources that were moved to the DB (gh endpoints and credentials - potentially providers in the future), and potentially offer a helm chart that folks can use.

It's so easy to over complicate things. Thanks for the reality check!
