### ISSUE TITLE
Please add FOSS Disclosure for your container release

### ISSUE THREAD

**Issue by schr3gl3j** [mercedes-benz/garm-operator#160]
please add foss disclosure for your container release.

<sup>Julian Schregle [julian.schregle@mercedes-benz.com](mailto:julian.schregle@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

**Comment by bavarianbidi** [comment]
@schr3gl3j what does that exactly mean?

We already add a SBOM document to our release. Should we push that beside the container image into the registry and publish the container image with that reference?

do you have some documentation how to do that?

**Comment by schr3gl3j** [comment]
yes I have seen the SBOM, but there are copyright notices missing and we found additional components in the docker container that are not included in the SBOM. 
As of now there are no suitable guides/checklists for the distribution of binaries or containers and this should be tackled from our side too, together with the garm-operator maintainer team :)
