### ISSUE TITLE
allow `pool` creation even if the referenced `image` doesn't exist yet

### ISSUE THREAD

**Issue by bavarianbidi** [mercedes-benz/garm-operator#18]
### What is the feature you would like to have?

At the moment it's not possible to create a `pool` CR when the referenced `image` CR doesn't exist.
This might cause some confusion as you have to need to know that the `image` must exist before a `pool` got created.

The common pattern for such cases in `kubernetes` is to requeue the reconciliation and try again.

* a pool CR can be created even if the referenced image doesn't exist
* once the referenced image CR got created, the pool get created in garm
* image update still works (updating the tag in the image-cr will update all pools where the image is used)

### Anything else you would like to add?

Similar to a `pod` spec it's possible to create a pod, even if the referenced `image` isn't available in the registry.
The `pod` controller is reconciling the pod-creation (with an exponential backoff) and once the image is available in the registry, the pod got scheduled.

**Comment by rafalgalaw** [comment]
closed with #76
