### ISSUE TITLE
Set `lastSyncTime` annotation on Custom Resources

### ISSUE THREAD

**Issue by rafalgalaw** [mercedes-benz/garm-operator#7]
### What steps did you take and what happened?

It would be cool to have a `lastSyncTime` annotation in our crds. Previously we had such field in our pool.Status which caused countless reconcile loops.

### What did you expect to happen?

Set annotation like in the following reference implementation:
[kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/inmemory/internal/cloud/runtime/cache/hooks.go#L34)

### garm version

v0.1.3

### garm-operator version

v0.1.0

### Kubernetes version

Kubernetes 1.25.5

**Comment by bavarianbidi** [comment]
I like the idea for having this information reflected back into CR (especially in combination with a custom `kube-state-metrics` configuration it should be quite easy to expose the last reconciliation Timestamp of the CR via a metric)
