### ISSUE TITLE
Fix Pool samples `spec.extraSpecs`

### ISSUE THREAD

**Issue by rafalgalaw** [mercedes-benz/garm-operator#8]
### What steps did you take and what happened?

The Pool samples still contain a wrong "" (empty string) value which causes the validating webhook to deny the pool resource

### What did you expect to happen?

Should be replaced by `extraSpecs: '{}'`

### garm version

v0.1.3

### garm-operator version

v0.1.0

### Kubernetes version

Kubernetes 1.25.5

**Comment by bavarianbidi** [comment]
As the documentation still needs a lot of improvements/working examples, let's keep in mind to fix this when working on https://github.com/mercedes-benz/garm-operator/issues/3
