### ISSUE TITLE
Show Runners

### ISSUE THREAD

**Issue by maigl** [mercedes-benz/garm-operator#9]
### What steps did you take and what happened?

I can't see the currently active runners with k9s :)

### What did you expect to happen?

The garm operator should reflect the currently active runners.

### garm version

all

### garm-operator version

 all

### Kubernetes version

 all

### Anything else you would like to add?

 no

**Comment by rafalgalaw** [comment]
currently testing an approach to reconcile on external events like for example a go routine, which periodically fetches runner instances from garm and writing these as events to a channel, on which the runner_controller can reconcile and create Runner CRs in the corresponding namespace:

```go
func (r *RunnerReconciler) SetupWithManager(mgr ctrl.Manager, eventChan chan event.GenericEvent) error {
	c, err := ctrl.NewControllerManagedBy(mgr).
		For(&garmoperatorv1alpha1.Runner{}).
		Build(r)
	if err != nil {
		return err
	}

	if err = c.Watch(&source.Channel{Source: eventChan}, &handler.EnqueueRequestForObject{}); err != nil {
		return err
	}
	return nil
}
```

**Comment by rafalgalaw** [comment]
See #23
